# Generated by Django 4.1 on 2023-05-09 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todos', '0003_todo_duration_todo_priority_todo_time_spent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTodo',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('title', models.CharField(max_length=100)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('todo', 'Todo'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('done', 'Done')], default='todo', max_length=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(default=0, help_text='Duration in minutes')),
                ('time_spent', models.PositiveIntegerField(default=0, help_text='Time spent in minutes')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('guest', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='guests.guest')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical todo',
                'verbose_name_plural': 'historical todos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
